### ISSUE TITLE
Any idea how Shecan works on Xbox, while this repository does not?

### ISSUE THREAD

**Issue by vfsoraki** [mosajjal/byosh#5]
Hello

I am using Shecan on my Xbox to connect to its services. Shecan works fine, while this repository does not.

I ran this code on a server and tried to see what domain Xbox tries to connect to. I got the list and added them, and I can sign in to my account after that. But still, Xbox services are not available.

My wild guess is that maybe Xbox tries to connect to ports other than 80/443, and this code does not handle them.

I may try to also implement a raw socket code, but in the mean time I wanted to inform you about this.

I also forked this repo to https://github.com/vfsoraki/byosh and made some changes. Biggest change is to move to docker-compose with two containers. More manageable, but that's more like my taste than anything else.

Also any idea on how we can also map other ports (tcp/udp both preferably)?

**Comment by mosajjal** [comment]
Hi,

Since I don't own an Xbox, I can't comment on why this is happening. If you can, please sniff the traffic on your router or by using `burp` or `mitmproxy` and attach a PCAP/log file so I can see what types of traffic we're supposed to pass through `byosh`.

for raw socket, there's always the possibility of breaking stuff since you'd be doing SSL termination which means any application with SSL pinning is not going to work properly. 

`docker-compose` is always a better practice and I'm keen to explore it but at the same time I wanted to keep this to the minimal and with fewest dependencies if possible. As an alternative, I might try to bundle all of this into a `go` binary rather than a Container. 

port change from 80/443 and 53 is not possible without changing client-side behavior, turning this into a Tunnel/VPN solution, which is not something I'd like to explore. There are many options available that can do that :)
